# Generated by Django 5.2.3 on 2025-06-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="desc",
            new_name="concern",
        ),
    ]
