# Generated by Django 5.2.3 on 2025-06-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_desc_contact_concern"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="email",
            new_name="Email",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="name",
            new_name="FullName",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="concern",
            new_name="YourMessage",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
    ]
