# Generated by Django 5.2.3 on 2025-06-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_email_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="Email",
            field=models.EmailField(max_length=254),
        ),
    ]
